### ISSUE TITLE
Create a bigdecimal-light.js

### ISSUE THREAD

**Issue by jamauro** [srknzl/bigdecimal.js#128]
**Is your feature request related to a problem? Please describe.**
This package looks great. Thanks for creating it. I wish the bundle size was quite a bit smaller though. Something on the order of `big.js`

**Describe the solution you'd like**
One idea would be to create a new package, maybe named `bigdecimal-light.js`, that has a comparable set of methods to `big.js`.

**Describe alternatives you've considered**
I don't think forking and removing the methods on my end would be a great solution but I guess it is possible.

Any interest in this idea?

**Comment by jamauro** [comment]
Hi, I'm not using webpack but I'm using a different bundler which is minifying your library. It looks to be working as expected in the browser which is great.

**Size comparison (minified)**
This library: `41.2kb`
Big.js: `6.94kb`

In terms of methods to keep, I think offering something comparable to the [big.js](https://mikemcl.github.io/big.js/#prototype-methods) set of methods would probably be about right.

**Comment by srknzl** [comment]
Ok thanks for the info. I will evaluate this and return to you.

**Comment by srknzl** [comment]
https://github.com/srknzl/bigdecimal.js/pull/143#issuecomment-1913647228
