### ISSUE TITLE
ES Modules

### ISSUE THREAD

**Issue by kavyarani7** [srknzl/bigdecimal.js#13]
Hi,

Thank you so much for this package. Its the one and permanent solution for the math blunder in JS. I was wondering if we could create ES Modules of the bigdecimal.js?

I tried creating wrapper around your files which would be a .mjs file. I could not make them work. Let me know if you would be interested in making ES module compatible files.

Regards
Kavya

**Comment by srknzl** [comment]
This is done. Make sure to try version 1.1.0 of the library with a node version that supports es modules. (e.g 12.22.x)

```js
import {Big, MC} from 'bigdecimal.js';


console.log(Big(15).add(Big(20), MC(1)).toString());

```
outputs:
```
4E+1
```

in version 1.1.0
