### ISSUE TITLE
No identifiers allowed directly after numeric literal

### ISSUE THREAD

**Issue by macdonaldr93** [srknzl/bigdecimal.js#15]
**Describe the bug**
I'm using your library to handle big numbers in my library: https://github.com/macdonaldr93/bloombug-money.

I'm building a React Native app with it and when I run the app I get `no identifiers allowed directly after numeric literal` with no stacktrace. I've debugged the issue to this library. I'm able to start a new project in expo, include this library, create a BigDecimal and it breaks.

**Expected behavior**
Work on Android.

**Screenshots**

**Environment (please complete the following information):**
- ReactNative and Expo
- Operating system Android
- BigDecimal.js version 1.1.0
- Node.js v16.13.0

**To Reproduce**

1. Start a new project in expo
2. Install this library
3. Create a BigDecimal and it breaks.

**Additional context**
For some reason, `big.js` doesn't have this issue.

**Comment by macdonaldr93** [comment]
I think I found the issue. It has to do with `1n` and numbers like that: https://github.com/srknzl/bigdecimal.js/blob/main/src/bigdecimal.ts#L3638

**Comment by srknzl** [comment]
Investigating, thanks for the issue.

**Comment by srknzl** [comment]
BigInt literals like 1n are supported in 16.13.0 as you can see from https://node.green/#ES2020-features-BigInt-basic-functionality I can clone and run your example in your library with Node 16.13.

This library requires a js runtime that has BigInt obviously. Also this library is intended to be used with Node.js. When using react native, runtime is not nodejs anymore. 

It looks like react native's runtime (as I understand JavaScriptCore and maybe something else on android) does not have BigInt support yet. Check out:

https://forum.dfinity.org/t/cant-find-variable-bigint-in-expo-react-native/5706
https://github.com/facebook/react-native/issues/28492

Looks like you can import and inject big-integer library as BigInt in your shim.js if BigInt does not exist in your react native runtime. Check out https://github.com/Balanced02/BigIntIssue for an example project.

**Comment by srknzl** [comment]
I suggest you to use big.js or other bigdecimal libraries if you need bigdecimal feature in environments where BigInt does not exist. My library's difference from big.js is the usage of BigInt and better performance for most operations due to that. Thank you for your understanding.

**Comment by macdonaldr93** [comment]
I used the BigInt shim and it worked perfectly. I tested big ints in Android and it worked. Sadly, it doesn't polyfill the literal. So I think if your library used `BigInt(1)` instead of `1n`, it would work.

**Comment by srknzl** [comment]
Ok I can do that for you. That will be probably 1.1.1 release.

**Comment by macdonaldr93** [comment]
Woohoo :) Thanks.

**Comment by macdonaldr93** [comment]
I'm testing out the patch this morning on my library too. I'll report back shortly.

**Comment by macdonaldr93** [comment]
I can confirm it works now. Not using a bigint literal and polyfilling `BigInt` with this is the solution.

```
import BigInt from 'big-integer';

if (typeof global.BigInt === 'undefined') {
  (global as any).BigInt = BigInt;
}
```

**Comment by macdonaldr93** [comment]
I have a branch ready to go, if you want. I'd love to contribute to this library :) I think you just need to enable access for me to open a pull request.

**Comment by srknzl** [comment]
You can always open a pr to any repository as I know. You just need to fork the repository and then create your branch there. 

Unfortunately, I have finalized my fix see #25. It includes an optimization too. Using BigInt constructors seemed to degrade performance of abs and compare functions, I solved the issue by caching some BigInts. Of course, I appreciate contributions but I saw your message too late for this one. Sorry :)

**Comment by srknzl** [comment]
1.1.1 is released https://www.npmjs.com/package/bigdecimal.js/v/1.1.1

**Comment by macdonaldr93** [comment]
Wow, that's awesome. It looks like it actually increased the performance a decent amount. Happy it worked it out :) Thanks for your help.
