### ISSUE TITLE
"Can't find variable: BigInt" error thrown on Safari 13

### ISSUE THREAD

**Issue by Sword-of-GraySkull** [srknzl/bigdecimal.js#160]
Issue:
"Can't find variable: BigInt" error is thrown on Safari 13 while app load

1. BigDecimal.js version: 1.3.0
2. Node.js version: 18.17.1
3. Operating system: macOS Catalina

Can we polyfill BigInt for browsers that do not support BigInt? Can JSBI be used for this case?

**Comment by srknzl** [comment]
hey, 

yes, only safari 14 and onwards has the BigInt type. First of all, this library is not designed for browsers, only for Node.js runtime.

> Can we polyfill BigInt for browsers that do not support BigInt? Can JSBI be used for this case?

not sure, but you can try I guess. This description from JSBI documentation is concerning though: 

> To use BigInts in code that you want to run everywhere, you need a library. But there’s a difficulty: the BigInt proposal changes the behavior of operators (like +, >=, etc.) to work on BigInts. These changes are impossible to polyfill directly; and they are also making it infeasible (in most cases) to transpile BigInt code to fallback code using Babel or similar tools. The reason is that such a transpilation would have to replace every single operator in the program with a call to some function that performs type checks on its inputs, which would incur an unacceptable performance penalty.

from https://github.com/GoogleChromeLabs/jsbi?tab=readme-ov-file#why

**Comment by srknzl** [comment]
closed as invalid, browsers not supported
