### ISSUE TITLE
Add markdown link checker to avoid broken links 

### ISSUE THREAD

**Issue by srknzl** [srknzl/bigdecimal.js#30]
Example workflow from hazelcast-nodejs-client: https://github.com/hazelcast/hazelcast-nodejs-client/blob/master/.github/workflows/markdown_link_checker.yml

**Comment by RishiKumarRay** [comment]
the given example in the link ,  we have to copy same ?

**Comment by srknzl** [comment]
Yeap, that will work I think. Go ahead if you want

**Comment by RishiKumarRay** [comment]
Okay I will generate a PR soon

**Comment by RishiKumarRay** [comment]
@srknzl please review
