### ISSUE TITLE
Big(1).divideWithMathContext(Big(3), new MC(0, RoundingMode.CEILING)).numberValue()

### ISSUE THREAD

**Issue by qingfengmy** [srknzl/bigdecimal.js#65]
**Describe the bug**
Big(1).divideWithMathContext(Big(3), new MC(0, RoundingMode.CEILING)).numberValue()

                    throw new RangeError('Non-terminating decimal expansion; no exact representable decimal result.');

1/3 ceiling  

i want the result is 1. What should I do?

**Comment by srknzl** [comment]
Closing because I think my reply solves your problem, reopen the issue if it does not.
