### ISSUE TITLE
Make `add`, `subtract`, `multiply`, `divide` & `compareTo` handle `any`

### ISSUE THREAD

**Issue by d-mon-** [srknzl/bigdecimal.js#80]
Hello!

I just noticed that the following functions [add](https://github.com/srknzl/bigdecimal.js/blob/main/src/bigdecimal.ts#L1745), [subtract](https://github.com/srknzl/bigdecimal.js/blob/main/src/bigdecimal.ts#L1811), [multiply](https://github.com/srknzl/bigdecimal.js/blob/main/src/bigdecimal.ts#L1847), [divideWithMathContext](https://github.com/srknzl/bigdecimal.js/blob/main/src/bigdecimal.ts#L1997) , [divideToIntegralValue](https://github.com/srknzl/bigdecimal.js/blob/main/src/bigdecimal.ts#L2317), [divideAndRemainder](https://github.com/srknzl/bigdecimal.js/blob/main/src/bigdecimal.ts#L2536) & [compareTo](https://github.com/srknzl/bigdecimal.js/blob/main/src/bigdecimal.ts#L2919) use [convertToBigDecimal](https://github.com/srknzl/bigdecimal.js/blob/main/src/bigdecimal.ts#L1185) to convert the incoming value as a safety measure. 
This code doesn't seem to be present in the Java source code though.
I guess it was done to prevent errors when developers aren't using typescript or to mitigate mistakes if they use it due to the nature of JS ? 

In order to match the (un)expected type, I guess it would make more sense to be more flexible and allow `any` or `BigDecimal | string | number` directly in those methods too ? this would also allow the following notation which happen to be less convoluted:
```diff
- bigValue.add(Big(1)).compareTo(Big(0))
+ bigValue.add(1).compareTo(0) 
```

**Comment by srknzl** [comment]
Can you checkout https://github.com/srknzl/bigdecimal.js/pull/82 and let me know if it is ok? @d-mon-
